add auth middleware to router
Ubivius/microservice-achievements pull request #32
Opened 2021-11-19 21:49 UTC by JeremiSavard

What changes does this PR contain?

add auth middleware for every call
Which JIRA ticket ID's are associated with this PR?

ubi-543
Additional comments and information

might break if game dev doesnt make changes on their side

2021-11-19 23:15 UTC, ysma500 requested changes

2021-11-19 23:15 UTC, ysma500 commented on chart/Chart.yaml
> +appVersion: 0.0.0-rc
You can remove that part, we'll talk later over why it will still work.

2021-11-19 23:15 UTC, ysma500 commented on chart/values.yaml
> +  tag: 0.0.0-rc
Same here :-/

2021-11-21 05:25 UTC, ArcticWalrus approved these changes

2021-11-22 23:48 UTC, ysma500 approved these changes
LGTM

2021-11-23 01:03 UTC, merged